---
- name: Template .config/monitors.xml
  ansible.builtin.template:
    src: "Gnome/.config/{{ template }}"
    dest: "{{ ansible_env.HOME }}/.config/monitors.xml"
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0664'
